### PR TITLE
[codegen] Add `SubscriptionItem.create_usage_record` method

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @rattrayalex-stripe 
cc @stripe/api-libraries

- [x] Sanity check for correctness.
- [x] Ensure appropriate test coverage (ie; write tests).

### CODE REVIEW

**Comment by ob-stripe** [comment]
Released as 2.35.0.

**Comment by rogerpine** [comment]
Is action='set' supported in create_usage_record? I only get the increment behavior. Set is meant to overwrite the full usage amount during the billing period.
Thank you.

**Comment by ob-stripe** [comment]
@rogerpine The library doesn't know about specific parameters, it simply passes parameters along to Stripe's API. So all parameters should be supported.

Are you observing an unexpected behavior when passing `action='set'`?

**Comment by rogerpine** [comment]
Yes, when I passed action='set', it was continuing to increment.

**Comment by remi-stripe** [comment]
@rogerpine `set` only works if you re-use the same timestamp for all your UsageRecords. If you pass a different timestamp each time it will still sum up to the total.

I'd recommend reaching out to our support team to discuss this instead: https://support.stripe.com/contact

**Pull request merged**
