### PR TITLE
Fix quality issues reported by DeepSource

### PR DESCRIPTION
**Pull request by sauravsrijan**
Fixes:
- PYL-C1801: Don't use len() to check for empty sequence
- PYL-W0612: Rename unused variable to `_`
- PYL-C0123: Use isinstance() for checking type

### CODE REVIEW

**Comment by ob-stripe** [comment]
Hi @sauravsrijan, thanks for the contribution! These changes look good to me, but it looks like one of the files is not passing the formatting check. Can you run `make fmt` to have Black format the code and amend the PR?

**Comment by sauravsrijan** [comment]
> Hi @sauravsrijan, thanks for the contribution! These changes look good to me, but it looks like one of the files is not passing the formatting check. Can you run `make fmt` to have Black format the code and amend the PR?

Hey @ob-stripe, I updated the PR. Please have a look.

**Comment by ob-stripe** [comment]
Awesome, thanks @sauravsrijan! Much appreciated.

**Comment by sauravsrijan** [comment]
No Problem! Looking forward to getting this PR merged!

**Comment by ob-stripe** [comment]
Released as 2.28.1.

**Comment by sauravsrijan** [comment]
Awesome! Thanks!

**Pull request merged**
