### PR TITLE
Logging form-data prior to processing form data.

### PR DESCRIPTION
**Pull request by jkeyes**

### CODE REVIEW

**Comment by jkeyes** [comment]
I don't know why the 2.7.13 build failed. Logs look okay.

**Comment by brandur-stripe** [comment]
Hey @jkeyes,

We only run `flake8` on one version of CI. There's a minor linting error here:

```
1.00s$ if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 stripe; fi
stripe/api_requestor.py:335:80: E501 line too long (83 > 79 characters)
The command "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 stripe; fi" exited with 1.
```

**Comment by brandur-stripe** [comment]
And thanks for the pull! I assume that you submitted this because what you were trying to do with sending a file blows up without the change?

**Comment by jkeyes** [comment]
@brandur-stripe Fixed that, thanks for the heads-up. Yeah, file uploads just weren't working for me, I reported on it in #377.

**Comment by brandur-stripe** [comment]
Thanks for sending your own fix! (And even the test case.)

LGTM.

**Comment by brandur-stripe** [comment]
Released as 1.75.3.

**Pull request merged**
