### PR TITLE
Adds 'partner_id' property to set_app_info hash

### PR DESCRIPTION
**Pull request by zachwick**
This adds support for an optional partner_id attribute in the SetAppInfo hash.

### CODE REVIEW

**Comment by ob-stripe** [comment]
Released in 1.83.0.

**Comment by ob-stripe** [comment]
I'm just realizing that if someone uses `set_app_info` with positional args instead of keyword args, then this is a breaking change :/

@brandur-stripe wdyt? Should we reorder the params?

**Comment by zachwick** [comment]
@ob-stripe @brandur-stripe There was some discussion that the arguments should be in alphabetical order, but I'm open to instead adding `partner_id` as the final argument instead.

**Comment by brandur-stripe** [comment]
> @brandur-stripe wdyt? Should we reorder the params?

Ah, good point. I'd probably just leave it as this point ... realistically the use of this feature in Python is probably still pretty minimal, and the use that we recommend in the README uses named parameters.

**Pull request merged**
