### PR TITLE
Update to_dict_recursive to work with lists of StripeObjects #695

### PR DESCRIPTION
**Pull request by soltanianalytics**
See https://github.com/stripe/stripe-python/issues/695

### CODE REVIEW

**Comment by paulasjes-stripe** [comment]
Hi @soltanianalytics, thanks for opening this! Would you be able to add some tests that cover this edge case?

**Comment by soltanianalytics** [comment]
Added a test, not sure why it's failing

**Comment by ob-stripe** [comment]
Hi @soltanianalytics, thanks for the contribution! I went with a slightly different approach to keep the implementation consistent with what we do in other languages, but the behavior should be the same. I hope you don't mind!

**Comment by soltanianalytics** [comment]
Happy to see that it was useful!

**Pull request closed without merging**
