### PR TITLE
Fix python 2.6 'zero length field name in format' error

### PR DESCRIPTION
**Pull request by vint21h**

### CODE REVIEW

**Comment by kyleconroy** [comment]
Gah, I always forget that 2.6 doesn't support the empty brackets in formatting. Thanks!

**Comment by vint21h** [comment]
Thanks for quick merge.
Please upload new code to PyPi.

**Comment by kyleconroy** [comment]
Done! https://pypi.python.org/pypi/stripe/1.24.1

**Comment by vint21h** [comment]
Thanks!

**Pull request merged**
