### PR TITLE
Try relative Python imports

### PR DESCRIPTION
**Pull request by brandur-stripe**
Moves from absolute imports to relative imports (i.e. prefix with a `.`
instead of a fully qualified `stripe.`).

I didn't change the test suite because it's not necessary and we might
want to move that out of the `stripe` module and into a `tests`
directory eventually anyway.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
@ob-stripe Any thoughts on this? :)

**Comment by ob-stripe** [comment]
\o/

And yeah, we ought to move the tests into their own directory at some point.

**Comment by ofek** [comment]
I disapprove of this change; it's less pythonic with no gain. I believe the person who opened the issue was simply not installing libraries correctly in GAE (I use it myself). Though, if this is approved, be sure to use `from __future__ import absolute_import`.

+1 to dedicated test directory though!

**Comment by ob-stripe** [comment]
Hey @ofek, thanks for the feedback! This tentative PR was motivated by the discussion in #315. The discussion is still ongoing, but for now @brandur-stripe and myself are leaning towards sticking with absolute imports as PEP 8 recommends.

**Comment by brandur-stripe** [comment]
+1 what @ob-stripe said. I wanted to see what this looked like, but we talk it through, and it doesn't seem like the way to go. I'm going to close this out for the time being.

**Pull request closed without merging**
