### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by brandur-stripe** [comment]
@ofek This looks sweet, thanks!

Just one note: I think that technically removing those `**params` globs on the `delete_discount` methods is a breaking change because if someone happens to be passing another argument into them, it won't work anymore. What do you think about leaving `**params` there for now and putting a comment in there to take those out on the next major version rev?

**Comment by ofek** [comment]
@brandur-stripe @ob-stripe Changes are complete but there is a major unrelated issue now. see https://github.com/stripe/stripe-python/issues/307

**Comment by brandur-stripe** [comment]
Thanks @ofek. Mind rebasing now that #308 is in? Thanks!

**Comment by ofek** [comment]
Rebased.

**Comment by brandur-stripe** [comment]
Looks good to me. Thanks!

**Pull request merged**
